<%@ page  pageEncoding="GB2312"%>

           <tr>
            <table width="778" border="0"  cellpadding="0" align="center" bgcolor="#E4EDFB">
             <tr>
                <td width="39.9"></td><td bgcolor="#000000" width="700.2"><img src="images/Spacer.gif" width="1" height="1"></td><td width="39.9"></td>
            </tr>
            <tr>
               <td hight="5">&nbsp;</td>
            </tr>
              <tr>
              <td></td>
                <td>
                  <p align="center">


</table>
<table width="778" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td><img src="./images/tail.jpg" width="778" height="130"></td>
  </tr>
</table>
</BODY>
</HTML>
