<%@ page  pageEncoding="GB2312"%>

<%@include file="../techSupport.jsp"%>


<HTML>
<HEAD>
<TITLE>
网上书店
</TITLE>
<!--CharSet-->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=gb2312">
<link rel="stylesheet" href="images/CSS.CSS" type="text/css">
<style type="text/css">
<!--
-->
</style>
<SCRIPT ID=clientEventHandlersJS LANGUAGE=javascript>
<!--

function window_onload() {
<!--Page.OnLoad-->
}

//-->
</SCRIPT>
</HEAD>
<BODY BGCOLOR=#3E79A6 leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" onload="return window_onload()">
<!--Counter-->
<!--Something Here-->
<table width="778" border="0" cellspacing="0" cellpadding="0" align="center" height="111">
  <tr>
    <td height="111" width="950" background="images/index_top3.jpg" valign="top">
    </td>
  </tr>
</table>
<table width="778" border="0" cellspacing="0" cellpadding="0" align="center" height="50">
  <tr bgcolor="#c4c4c4" height="5">
    <td>&nbsp;&nbsp;
	  <div align="left"><b>
<!--Language-->
网上书店欢迎您！
<!--Something Here-->
		</b>
	  </div>
	</td>
  </tr>
  <tr>
    <td valign="top">
      <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" height="28">
        <tr>
		<td width="14%">
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28" >
              <tr>
                <td width="100%">
                  <div align="center"><b><a href="index.jsp"><font color="#FFFFFF">用户登录</font></a></b>
                  </div>
                </td>
              </tr>
            </table>
          </td>
<!--Button1.Content.Begin-->
          <td width="14%">
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28">
              <tr>
                <td width="100%">
                  <div align="center"><b>
<!--Button1.Link-->
<a href="#">
<font color="#FFFFFF">
<!--Button1-->
书店简介
</font></a></b>
                  </div>
                </td>
              </tr>
            </table>
          </td>
<!--Button1.Content.End-->

<!--Button2.Content.Begin-->
          <td width="14%">
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28">
              <tr>
                <td width="100%">
                  <div align="center"><b>
<!--Button2.Link-->
<a href="main.jsp">
<font color="#FFFFFF">
<!--Button2-->
新书介绍
                          </font></a></b></div>
                </td>
              </tr>
            </table>
          </td>
<!--Button2.Content.End-->

<

<!--Button4.Content.Begin-->
          <td width="14%">
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28" >
              <tr>
                <td width="100%">
                  <div align="center"><b>
<!--Button4.Link-->
<a href="message.jsp">
<font color="#FFFFFF">
<!--Button4-->
留言板
                          </font></a></b></div>
                </td>
              </tr>
            </table>
          </td>
<!--Button4.Content.End-->


<!--Button6.Content.Begin-->
          <td width="16%">
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28" >
              <tr>
                <td width="100%">
                  <div align="center"><b>
<!--Button6.Link-->
<a href="admin/adm_login.jsp">
<font color="#FFFFFF">
<!--Button6-->
管理员入口
</font></a>
                    </b></div>
                </td>
              </tr>
            </table>
          </td>
<!--Button6.Content.End-->




        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="778" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#E4EDFB">
  <tr>
    <td valign="top">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td>
<!--IndexPage.Content.Begin-->
            <table width="90%" border="0" cellspacing="0" cellpadding="0" align="center">
              <tr>
                <td bgcolor="#000000"><img src="images/Spacer.gif" width="1" height="1"></td>
              </tr>
              <tr>
