<%@ page  pageEncoding="GB2312" %>
 <tr>
 <td>
<!--SubButton1.Content.Begin-->
<!--SubButton.Front-->
<!--Something Here-->
<!--SubButton1.Link-->
<a href="booklist.jsp">
<!--SubButton1-->
在线购书
 </a>
<!--SubButton.Back-->
 |
<!--SubButton1.Content.End-->

<!--SubButton2.Content.Begin-->
<!--SubButton2.Link-->
<a href="shopcar.jsp">
<!--SubButton2-->
我的购物车
</a> |
<!--SubButton2.Content.End-->

<!--SubButton3.Content.Begin-->
<!--SubButton3.Link-->
<a href="info.jsp">
<!--SubButton3-->
订单信息
 </a> |
<!--SubButton3.Content.End-->

<!--SubButton4.Content.Begin-->
<!--SubButton4.Link-->
<a href="showUserPoint.jsp">
<!--SubButton4-->
用户积分/等级
 </a> |
 
  <!--SubButton5.Content.Begin-->
<!--SubButton5.Link-->
<a href="userinfo.jsp">
用户资料
 </a> 
 
 <!--SubButton6.Content.Begin-->
<!--SubButton6.Link-->
<a href="modifyUser.jsp">
修改资料
 </a> |

<!--SubButton7.Content.Begin-->
<!--SubButton7.Link-->
<a href="showSaleStatistics.jsp">
<!--SubButton-->
图书销售排行
 </a> |
 
<!--SubButton8.Content.Begin-->
<!--SubButton8.Link-->
<a href="logout.jsp">
登录/注销
 </a> |



</td>
</tr>
<tr>
                <td bgcolor="#000000"><img src="images/Spacer.gif" width="1" height="1"></td>
</tr>
